### ISSUE TITLE
Error: Python executable is v3.6.4, which is not supported by gyp

### ISSUE THREAD

**Issue by conradwt** [gobuffalo/buffalo#1065]
--- DELETE ABOVE --

## Steps to Reproduce the Problem

  1.  go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo
  2.  cd $GOPATH/src/github.com/$USER/
  3.  buffalo new december

## Expected Behavior

I expected that the command would complete successfully.

## Actual Behavior

The command didn't complete successfully and I getting the following error message:

```
$ buffalo new december
      create  .buffalo.dev.yml
      create  assets/images/logo.svg
      create  assets/css/application.scss
      create  assets/images/favicon.ico
      create  assets/js/application.js
      create  .babelrc
      create  package.json
      create  public/assets/.keep
      create  webpack.config.js
         run  yarn install --no-progress --save
yarn install v1.6.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
error /Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-sass
Output:
Building: /usr/local/bin/node /Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@10.1.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/Users/conradwt/anaconda3/bin/python" in the PATH
gyp verb `which` succeeded /Users/conradwt/anaconda3/bin/python /Users/conradwt/anaconda3/bin/python
gyp verb check python version `/Users/conradwt/anaconda3/bin/python -c "import platform; print(platform.python_version());"` returned: "3.6.4\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/conradwt/anaconda3/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:273:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:378:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:598:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/conradwt/go.dir/gocode/src/github.com/conradwt/december/node_modules/node-sass
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
```

## Info

<details>

```bash
$ buffalo info
### Buffalo Version
v0.11.1

### App Information
Pwd=/Users/conradwt/go.dir/gocode/src/github.com/conradwt
Root=/Users/conradwt/go.dir/gocode/src/github.com/conradwt
GoPath=/Users/conradwt/go.dir/gocode
Name=conradwt
Bin=bin/conradwt
PackagePkg=github.com/conradwt
ActionsPkg=github.com/conradwt/actions
ModelsPkg=github.com/conradwt/models
GriftsPkg=github.com/conradwt/grifts
VCS=
WithPop=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=false
WithGrifts=false

### Go Version
go version go1.10.2 darwin/amd64

### Go Env
GOARCH="amd64"
GOBIN="/Users/conradwt/go.dir/gocode/bin"
GOCACHE="/Users/conradwt/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/conradwt/go.dir/gocode"
GORACE=""
GOROOT="/opt/local/lib/go"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vh/mc6hdgd94x3fzwkxvk7y9jvw0000gn/T/go-build545758923=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Node Version
v10.1.0

### NPM Version
6.0.1

### Yarn Version
1.6.0

### PostgreSQL Version
pg_ctl (PostgreSQL) 10.4

### MySQL Version
MySQL Not Found

### SQLite Version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2171d

### Dep Version
dep Not Found

### Dep Status
dep Not Found

</details>

This appears to be a Node package (i.e. node-gyp) and library, gyp, issue.  Is there any way to configure the path of the Python executable within a Buffalo project?

**Comment by conradwt** [comment]
After performing the following actions I was able to successfuly create a project:

1.  reset the PRAM

2.  uninstall `node-gyp`

3.  install `node-gyp`

4. export PYTHON=/usr/bin/python

5. buffalo new december (took about 3 minutes of so)

Next, there appears to be a lot of discussion about the possibility of using another build being that node-gyp depends on Python 2.7.

**Comment by conradwt** [comment]
If you have multiple versions of Python like myself, then one can resolve the issue by using the following method:

```bash
PYTHON=python2.7 buffalo new some_project_name
```

Another option would be to add this as an alias to your `.bashrc` or `.profile`.

**Comment by duffn** [comment]
I can't currently recreate this.

```bash
% python -V
Python 3.6.4
% go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo
...
INFO[0032] Congratulations! Your application, december, has been successfully built!
```

**Comment by conradwt** [comment]
@stanislas-m Yes, I agree that this probably was fixed on the `node-gyp`.  However, it’s the responsibility of the `buffalo` project to keep a close eye on this and other 3rd party dependencies.

**Comment by stanislas-m** [comment]
While I agree we need to ensure it still work, that's the role of some
tests we already wrote since the issue was opened. If a new bug occurs
with node-gyp, we'll take care of it, but we don't need to keep this
particular issue open forever.Le jeudi 27 décembre 2018 à 10:07 -0800,
Conrad Taylor a écrit :

**Comment by stanislas-m** [comment]
@conradwt I understand, and that's the problem when people work on a project on their free time. :)

Now, if you think this issue should be documented somewhere, then can I ask you to add an entry in the `Troubleshooting` section in the docs? https://gobuffalo.io/en/docs/troubleshooting (source: https://github.com/gobuffalo/gobuffalo/blob/master/templates/docs/troubleshooting.html) Thanks!

**Comment by conradwt** [comment]
@stanislas-m At this time, I would only document issues which can be reproduced within the current release of the software.  Please have a good day.

**Comment by paulosoares86** [comment]
This error did happen with me as well. Looks like some lib cannot find python2 executable. Making a symbolic link solved my problem: 
```ln -s /usr/bin/python2.7 /usr/bin/python2```

**Comment by bilus** [comment]
Happened for me as well:

```
Building: /usr/local/Cellar/node/14.5.0/bin/node /Users/martinb/dev/rally/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/14.5.0/bin/node',
gyp verb cli   '/Users/martinb/dev/rally/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.5.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/martinb/dev/rally/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/martinb/dev/rally/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/martinb/dev/rally/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/martinb/dev/rally/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/martinb/dev/rally/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/martinb/dev/rally/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/martinb/dev/rally/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/martinb/dev/rally/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/martinb/dev/rally/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/martinb/dev/rally/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/martinb/dev/rally/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/martinb/dev/rally/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /Users/martinb/.pyenv/shims/python
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/martinb/.pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:442:11)
gyp ERR! stack     at Socket.emit (events.js:314:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:673:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/14.5.0/bin/node" "/Users/martinb/dev/rally/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/martinb/dev/rally/node_modules/node-sass
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```
