### ISSUE TITLE
`bin/gothrecipe migrate` panic: sql: Register called twice for driver postgres

### ISSUE THREAD

**Issue by drnic** [gobuffalo/buffalo#1127]
In the https://github.com/gobuffalo/gothrecipe project I get an error when using the `buffalo build`'s binary's `migrate` subcommand.

`buffalo db migrate` works as expected:

```
$ buffalo db migrate
v4.5.10

> create_users
> create_widgets

0.1183 seconds
dumped schema for gothrecipe_development
```

But `bin/gothrecipe migrate` fails:

```
$ buffalo db drop -a
$ buffalo db create -a
$ buffalo build
$ bin/gothrecipe migrate
panic: sql: Register called twice for driver postgres

goroutine 1 [running]:
database/sql.Register(0x1a801bb, 0x8, 0x1c2cf00, 0x2118128)
	/usr/local/Cellar/go/1.10.3/libexec/src/database/sql/sql.go:50 +0x1a4
github.com/gobuffalo/gothrecipe/vendor/github.com/lib/pq.init.0()
	/Users/drnic/Projects/gopath/src/github.com/gobuffalo/gothrecipe/vendor/github.com/lib/pq/conn.go:49 +0x5c
```

This issue was originally raised in #1123 but was not related to initial issue.

**Comment by markbates** [comment]
Fixed with #1126
