### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yageek** [gobuffalo/buffalo#120]
I just installed the last version of `buffalo` and I have the following error after calling `buffalo new coke`:

```
## Long stuff before
npm WARN coke@1.0.0 No repository field.
--> /Users/yheinrich/dev/go/src/gitlab.com/yageek/coke/models/models.go
--> go get github.com/markbates/pop/...
--> go install github.com/markbates/pop/soda
--> database.yml
--> go get -t ./...
--> goimports -w .
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xbd6cf8 pc=0x10b4e]

runtime stack:
runtime.throw(0x1ef16a, 0x2a)
	/usr/local/opt/go/libexec/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/opt/go/libexec/src/runtime/sigpanic_unix.go:12 +0x2cc
runtime.lfstackpop(0x3036a8, 0xc42028be90)
	/usr/local/opt/go/libexec/src/runtime/lfstack.go:41 +0x4e
runtime.getempty(0x8af800)
	/usr/local/opt/go/libexec/src/runtime/mgcwork.go:311 +0x7c
runtime.(*gcWork).put(0xc42001dc28, 0xc4207b4860)
	/usr/local/opt/go/libexec/src/runtime/mgcwork.go:110 +0x9a
runtime.greyobject(0xc4207b4860, 0x0, 0x0, 0xc41ffc25bc, 0xc400000000, 0x796390, 0xc42001dc28, 0x43)
	/usr/local/opt/go/libexec/src/runtime/mgcmark.go:1243 +0x12d
runtime.shade(0xc4207b4860)
	/usr/local/opt/go/libexec/src/runtime/mgcmark.go:1180 +0xb3
runtime.gcmarkwb_m(0xc42443ef18, 0xc4207b4860)
	/usr/local/opt/go/libexec/src/runtime/mbarrier.go:105 +0x5b
runtime.writebarrierptr_nostore1.func1()
	/usr/local/opt/go/libexec/src/runtime/mbarrier.go:131 +0x64
runtime.systemstack(0xc42001f500)
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/opt/go/libexec/src/runtime/proc.go:1078

goroutine 720 [running]:
runtime.systemstack_switch()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:252 fp=0xc420038e80 sp=0xc420038e78
runtime.writebarrierptr_nostore1(0xc42443ef18, 0xc4207b4860)
	/usr/local/opt/go/libexec/src/runtime/mbarrier.go:132 +0xb6 fp=0xc420038ec0 sp=0xc420038e80
runtime.writebarrierptr_nostore(0xc42443ef18, 0xc4207b4860)
	/usr/local/opt/go/libexec/src/runtime/mbarrier.go:170 +0x49 fp=0xc420038ee0 sp=0xc420038ec0
runtime.heapBitsBulkBarrier(0xc42443ef10, 0x10)
	/usr/local/opt/go/libexec/src/runtime/mbitmap.go:618 +0xcf fp=0xc420038f40 sp=0xc420038ee0
runtime.typedmemmove(0x196f80, 0xc42443ef10, 0xc423b8ef10)
	/usr/local/opt/go/libexec/src/runtime/mbarrier.go:183 +0x65 fp=0xc420038f78 sp=0xc420038f40
runtime.growslice(0x196f80, 0xc423990000, 0x8ac00, 0x8ac00, 0x8ac01, 0xc423990000, 0x6f000, 0x8ac00)
	/usr/local/opt/go/libexec/src/runtime/slice.go:136 +0x1b3 fp=0xc420039008 sp=0xc420038f78
go/parser.(*parser).parseElementList(0xc42061a300, 0xc423990000, 0x8ac00, 0x8ac00)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1337 +0x181 fp=0xc420039070 sp=0xc420039008
go/parser.(*parser).parseLiteralValue(0xc42061a300, 0x2ee5a0, 0xc42050d920, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1356 +0x1c6 fp=0xc4200390d8 sp=0xc420039070
go/parser.(*parser).parsePrimaryExpr(0xc42061a300, 0x100, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1502 +0x404 fp=0xc420039138 sp=0xc4200390d8
go/parser.(*parser).parseUnaryExpr(0xc42061a300, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1582 +0x415 fp=0xc4200391d0 sp=0xc420039138
go/parser.(*parser).parseBinaryExpr(0xc42061a300, 0x0, 0x1, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1599 +0x73 fp=0xc420039268 sp=0xc4200391d0
go/parser.(*parser).parseExpr(0xc42061a300, 0x100, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1624 +0x5e fp=0xc4200392a0 sp=0xc420039268
go/parser.(*parser).parseValue(0xc42061a300, 0xc42061a300, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1299 +0xa5 fp=0xc4200392e8 sp=0xc4200392a0
go/parser.(*parser).parseElement(0xc42061a300, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1325 +0xbd fp=0xc420039348 sp=0xc4200392e8
go/parser.(*parser).parseElementList(0xc42061a300, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1337 +0x8c fp=0xc4200393b0 sp=0xc420039348
go/parser.(*parser).parseLiteralValue(0xc42061a300, 0x2eede0, 0xc42050d8f0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1356 +0x1c6 fp=0xc420039418 sp=0xc4200393b0
go/parser.(*parser).parsePrimaryExpr(0xc42061a300, 0xc42045d300, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1502 +0x404 fp=0xc420039478 sp=0xc420039418
go/parser.(*parser).parseUnaryExpr(0xc42061a300, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1582 +0x415 fp=0xc420039510 sp=0xc420039478
go/parser.(*parser).parseBinaryExpr(0xc42061a300, 0x0, 0x1, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1599 +0x73 fp=0xc4200395a8 sp=0xc420039510
go/parser.(*parser).parseExpr(0xc42061a300, 0xc420250400, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:1624 +0x5e fp=0xc4200395e0 sp=0xc4200395a8
go/parser.(*parser).parseExprList(0xc42061a300, 0xc42061a300, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:568 +0x80 fp=0xc420039648 sp=0xc4200395e0
go/parser.(*parser).parseRhsList(0xc42061a300, 0x0, 0x0, 0x1)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:608 +0x42 fp=0xc420039688 sp=0xc420039648
go/parser.(*parser).parseValueSpec(0xc42061a300, 0x0, 0x55, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:2282 +0x52e fp=0xc420039748 sp=0xc420039688
go/parser.(*parser).(go/parser.parseValueSpec)-fm(0x0, 0x55, 0x0, 0x40, 0xc42098fb40)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:2427 +0x48 fp=0xc420039788 sp=0xc420039748
go/parser.(*parser).parseGenDecl(0xc42061a300, 0x55, 0xc420039878, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:2356 +0x38c fp=0xc420039840 sp=0xc420039788
go/parser.(*parser).parseDecl(0xc42061a300, 0x1febc0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:2442 +0xa4 fp=0xc420039898 sp=0xc420039840
go/parser.(*parser).parseFile(0xc42061a300, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/parser.go:2488 +0x38f fp=0xc4200399a0 sp=0xc420039898
go/parser.ParseFile(0xc42062ce40, 0xc420418cc0, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/go/parser/interface.go:121 +0x1dc fp=0xc420039a28 sp=0xc4200399a0
golang.org/x/tools/imports.loadExportsGoPath(0xc42022af59, 0x1, 0xc420363c80, 0x47, 0x0)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:573 +0x319 fp=0xc420039e40 sp=0xc420039a28
golang.org/x/tools/imports.findImportGoPath.func1.1(0xc420330f00, 0xc42022af59, 0x1, 0xc4205baf98, 0xc420232060, 0xc4202c0660, 0xc4203ea900)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:719 +0xaf fp=0xc420039f68 sp=0xc420039e40
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420039f70 sp=0xc420039f68
created by golang.org/x/tools/imports.findImportGoPath.func1
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:733 +0x1a5

goroutine 1 [chan receive]:
golang.org/x/tools/imports.fixImports(0xc42021cbc0, 0xc42008cb80, 0xc42022ae20, 0xf, 0xd2, 0x600, 0x2ec750, 0xc42008cb80, 0x0)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:174 +0x66b
golang.org/x/tools/imports.Process(0xc42022ae20, 0xf, 0xc4201fe600, 0xd2, 0x600, 0x2ec750, 0x0, 0x0, 0x4a1, 0x0, ...)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/imports.go:58 +0x755
main.processFile(0xc42022ae20, 0xf, 0x0, 0x0, 0x2ed5a0, 0xc42002a010, 0x2, 0x0, 0x0)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/cmd/goimports/goimports.go:138 +0x164
main.visitFile(0xc42022ae20, 0xf, 0x2efd20, 0xc42021e680, 0x0, 0x0, 0x0, 0x0)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/cmd/goimports/goimports.go:173 +0xdd
path/filepath.walk(0xc42022ae20, 0xf, 0x2efd20, 0xc42021e680, 0x1fecc0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0xc420012979, 0x7, 0x2efd20, 0xc4200675f0, 0x1fecc0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:376 +0x344
path/filepath.walk(0x7fff5fbff935, 0x1, 0x2efd20, 0xc4200671e0, 0x1fecc0, 0x0, 0xc420067110)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0x7fff5fbff935, 0x1, 0x1fecc0, 0x0, 0xc420067110)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:398 +0xd5
main.walkDir(0x7fff5fbff935, 0x1)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/cmd/goimports/goimports.go:182 +0x41
main.gofmtMain()
	/Users/yheinrich/dev/go/src/golang.org/x/tools/cmd/goimports/goimports.go:273 +0x215
main.main()
	/Users/yheinrich/dev/go/src/golang.org/x/tools/cmd/goimports/goimports.go:191 +0x32

goroutine 5 [chan receive]:
golang.org/x/tools/imports.findImportGoPath(0xc42022af59, 0x1, 0xc420232060, 0xc42022ae20, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:737 +0x81a
golang.org/x/tools/imports.fixImports.func2(0xc42022ae20, 0xf, 0xc420065080, 0xc42022af59, 0x1, 0xc420232060)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:164 +0x7b
created by golang.org/x/tools/imports.fixImports
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:170 +0x5bc

goroutine 15 [select]:
golang.org/x/tools/imports.findImportGoPath.func1(0xc420536000, 0x370, 0x400, 0xc420330f00, 0xc4203ea900, 0xc4205fc000, 0x370, 0x370, 0xc42022af59, 0x1, ...)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:702 +0x22b
created by golang.org/x/tools/imports.findImportGoPath
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:735 +0x7c1

goroutine 747 [select]:
golang.org/x/tools/imports.findImportGoPath.func1.1(0xc420330f00, 0xc42022af59, 0x1, 0xc42358f848, 0xc420232060, 0xc4202c0780, 0xc4203ea900)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:729 +0x232
created by golang.org/x/tools/imports.findImportGoPath.func1
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:733 +0x1a5

goroutine 729 [select]:
golang.org/x/tools/imports.findImportGoPath.func1.1(0xc420330f00, 0xc42022af59, 0x1, 0xc423968000, 0xc420232060, 0xc4202c06c0, 0xc4203ea900)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:729 +0x232
created by golang.org/x/tools/imports.findImportGoPath.func1
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:733 +0x1a5

goroutine 770 [select]:
golang.org/x/tools/imports.findImportGoPath.func1.1(0xc420330f00, 0xc42022af59, 0x1, 0xc4205be048, 0xc420232060, 0xc4202c0720, 0xc4203ea900)
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:729 +0x232
created by golang.org/x/tools/imports.findImportGoPath.func1
	/Users/yheinrich/dev/go/src/golang.org/x/tools/imports/fix.go:733 +0x1a5
Error: exit status 2
```
I'm using `go version go1.7.3 darwin/amd64`

**Comment by markbates** [comment]
It looks like a problem with `goimports`. Perhaps try to recompile `goimports` with the latest version of it, and see if that helps.

**Comment by yageek** [comment]
I just updated both `go` and `goimports` and it seems to work. Any option to avoid those errors during the installation?

**Comment by markbates** [comment]
If `goimports` isn't installed, then Buffalo defaults to using `go fmt`. In this case it looks like you just had a corrupted, or an out of date installation of it. I've never seen `goimports` panic like this before. You may want to consider opening an issue with that project with this stack trace, see if Brad has any ideas as to why that happens.
