### ISSUE TITLE
Race condition panic with Buffalo v0.13.0 events

### ISSUE THREAD

**Issue by duckbrain** [gobuffalo/buffalo#1384]
## Description

I'm getting an application crash on moving to Buffalo v0.13.0 today. It appears to be a race condition related to the new events feature. The crash happens somewhat randomly when I start up my application. My application does have a route that's called that starts a lot of go routines.

### Relevant call stack

<details>

```
fatal error: concurrent map iteration and map write

goroutine 13837 [running]:
runtime.throw(0xc9bcaf, 0x26)
        /usr/lib/go/src/runtime/panic.go:608 +0x72 fp=0xc000a4b120 sp=0xc000a4b0f0 pc=0x42c992
runtime.mapiternext(0xc000a4b1e8)
        /usr/lib/go/src/runtime/map.go:790 +0x525 fp=0xc000a4b1a8 sp=0xc000a4b120 pc=0x4107e5
github.com/gobuffalo/buffalo.(*DefaultContext).Data(0xc0002cb180, 0xc00024a5b0)
        $GOPATH/src/github.com/gobuffalo/buffalo/default_context.go:222 +0xac fp=0xc000a4b258 sp=0xc000a4b1a8 pc=0xa7ec6c
github.com/gobuffalo/buffalo.(*DefaultContext).MarshalJSON(0xc0002cb180, 0xc551c0, 0xc0002cb180, 0x7eff8c51d178, 0xc0002cb180, 0xc000288201)
        $GOPATH/src/github.com/gobuffalo/buffalo/default_context.go:262 +0x4e fp=0xc000a4b328 sp=0xc000a4b258 pc=0xa7f25e
encoding/json.marshalerEncoder(0xc0006eb600, 0xc551c0, 0xc0002cb180, 0x16, 0xc0002c0100)
        /usr/lib/go/src/encoding/json/encode.go:453 +0xb7 fp=0xc000a4b3a8 sp=0xc000a4b328 pc=0x4f9847
encoding/json.(*encodeState).reflectValue(0xc0006eb600, 0xc551c0, 0xc0002cb180, 0x16, 0xc0002c0100)
        /usr/lib/go/src/encoding/json/encode.go:333 +0x82 fp=0xc000a4b3e0 sp=0xc000a4b3a8 pc=0x4f8f32
encoding/json.interfaceEncoder(0xc0006eb600, 0xb982e0, 0xc000900eb0, 0x94, 0xc000900100)
        /usr/lib/go/src/encoding/json/encode.go:619 +0xab fp=0xc000a4b428 sp=0xc000a4b3e0 pc=0x4fb18b
encoding/json.(*mapEncoder).encode(0xc0000ba0c0, 0xc0006eb600, 0xb9c300, 0xc000110540, 0x15, 0xb90100)
        /usr/lib/go/src/encoding/json/encode.go:692 +0x37b fp=0xc000a4b598 sp=0xc000a4b428 pc=0x4fbceb
encoding/json.(*mapEncoder).encode-fm(0xc0006eb600, 0xb9c300, 0xc000110540, 0x15, 0xc000a40100)
        /usr/lib/go/src/encoding/json/encode.go:708 +0x64 fp=0xc000a4b5d8 sp=0xc000a4b598 pc=0x505c34
encoding/json.(*encodeState).reflectValue(0xc0006eb600, 0xb9c300, 0xc000110540, 0x15, 0x12a0100)
        /usr/lib/go/src/encoding/json/encode.go:333 +0x82 fp=0xc000a4b610 sp=0xc000a4b5d8 pc=0x4f8f32
encoding/json.(*encodeState).marshal(0xc0006eb600, 0xb9c300, 0xc000110540, 0xd4c30100, 0x0, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:305 +0xf4 fp=0xc000a4b658 sp=0xc000a4b610 pc=0x4f89e4
encoding/json.Marshal(0xb9c300, 0xc000110540, 0xc7fc8c, 0x7, 0xc0002882e8, 0x0, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:160 +0x52 fp=0xc000a4b6d0 sp=0xc000a4b658 pc=0x4f82b2
github.com/gobuffalo/mapi.Mapi.MarshalJSON(0xc000110180, 0xbf3d20, 0xc000110180, 0x7eff8c51d158, 0xc000110180, 0xc000288101)
        $GOPATH/src/github.com/gobuffalo/mapi/mapi.go:70 +0x4da fp=0xc000a4b830 sp=0xc000a4b6d0 pc=0x9dceaa
encoding/json.marshalerEncoder(0xc0001ace70, 0xbf3d20, 0xc000110180, 0x15, 0xc000110100)
        /usr/lib/go/src/encoding/json/encode.go:453 +0xb7 fp=0xc000a4b8b0 sp=0xc000a4b830 pc=0x4f9847
encoding/json.(*encodeState).reflectValue(0xc0001ace70, 0xbf3d20, 0xc000110180, 0x15, 0xc000110100)
        /usr/lib/go/src/encoding/json/encode.go:333 +0x82 fp=0xc000a4b8e8 sp=0xc000a4b8b0 pc=0x4f8f32
encoding/json.interfaceEncoder(0xc0001ace70, 0xb982e0, 0xc000900050, 0x94, 0xc000900100)
        /usr/lib/go/src/encoding/json/encode.go:619 +0xab fp=0xc000a4b930 sp=0xc000a4b8e8 pc=0x4fb18b
encoding/json.(*mapEncoder).encode(0xc0000ba0c0, 0xc0001ace70, 0xb9c300, 0xc0001101b0, 0x15, 0xb90100)
        /usr/lib/go/src/encoding/json/encode.go:692 +0x37b fp=0xc000a4baa0 sp=0xc000a4b930 pc=0x4fbceb
encoding/json.(*mapEncoder).encode-fm(0xc0001ace70, 0xb9c300, 0xc0001101b0, 0x15, 0xc0005d0100)
        /usr/lib/go/src/encoding/json/encode.go:708 +0x64 fp=0xc000a4bae0 sp=0xc000a4baa0 pc=0x505c34
encoding/json.(*encodeState).reflectValue(0xc0001ace70, 0xb9c300, 0xc0001101b0, 0x15, 0xbd0100)
        /usr/lib/go/src/encoding/json/encode.go:333 +0x82 fp=0xc000a4bb18 sp=0xc000a4bae0 pc=0x4f8f32
encoding/json.(*encodeState).marshal(0xc0001ace70, 0xb9c300, 0xc0001101b0, 0x1c730100, 0x0, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:305 +0xf4 fp=0xc000a4bb60 sp=0xc000a4bb18 pc=0x4f89e4
encoding/json.Marshal(0xb9c300, 0xc0001101b0, 0xc803d9, 0x7, 0xc0002881b8, 0xc0005dfc98, 0x46d7fb)
        /usr/lib/go/src/encoding/json/encode.go:160 +0x52 fp=0xc000a4bbd8 sp=0xc000a4bb60 pc=0x4f82b2
github.com/gobuffalo/events.Event.MarshalJSON(0xc8ca4c, 0x15, 0x0, 0x0, 0xc000110180, 0x0, 0x0, 0x40bd93, 0xbbac40, 0xc32de0, ...)
        $GOPATH/src/github.com/gobuffalo/events/event.go:43 +0x10a fp=0xc000a4bc50 sp=0xc000a4bbd8 pc=0xa2566a
github.com/gobuffalo/events.(*Event).MarshalJSON(0xc000418040, 0xc32de0, 0xc000418040, 0x7eff8c51d138, 0xc000418040, 0x1)
        <autogenerated>:1 +0x5f fp=0xc000a4bcc0 sp=0xc000a4bc50 pc=0xa2742f
encoding/json.marshalerEncoder(0xc0001acd10, 0xc32de0, 0xc000418040, 0x99, 0xc0005d0100)
        /usr/lib/go/src/encoding/json/encode.go:453 +0xb7 fp=0xc000a4bd40 sp=0xc000a4bcc0 pc=0x4f9847
encoding/json.(*encodeState).reflectValue(0xc0001acd10, 0xc32de0, 0xc000418040, 0x99, 0xbd0100)
        /usr/lib/go/src/encoding/json/encode.go:333 +0x82 fp=0xc000a4bd78 sp=0xc000a4bd40 pc=0x4f8f32
encoding/json.(*encodeState).marshal(0xc0001acd10, 0xc32de0, 0xc000418040, 0x100, 0x0, 0x0)
        /usr/lib/go/src/encoding/json/encode.go:305 +0xf4 fp=0xc000a4bdc0 sp=0xc000a4bd78 pc=0x4f89e4
encoding/json.Marshal(0xc32de0, 0xc000418040, 0xc32de0, 0xc000418040, 0x1c, 0xc0002fd450, 0x8)
        /usr/lib/go/src/encoding/json/encode.go:160 +0x52 fp=0xc000a4be38 sp=0xc000a4bdc0 pc=0x4f82b2
github.com/gobuffalo/events.LoadPlugins.func1.1.1(0xc8ca4c, 0x15, 0x0, 0x0, 0xc000110180, 0x0, 0x0)
        $GOPATH/src/github.com/gobuffalo/events/plugins.go:32 +0xac fp=0xc000a4bfa8 sp=0xc000a4be38 pc=0xa26a7c
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000a4bfb0 sp=0xc000a4bfa8 pc=0x459af1
created by github.com/gobuffalo/events.(*manager).Emit.func1
        $GOPATH/src/github.com/gobuffalo/events/manager.go:84 +0x1a8
```

</details>

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Start my applciation with a route that uses lots of go routines that do database queries.
  1. Refresh until it panics
  1. Look at the stack traces in sadness

### Expected Behavior

I expected my program to run like it did before the update.

Don't panic. (In big friendly letters.)

### Actual Behavior

It paniced after 1-3 loads every time.

> I think the description for "Actual Behavior" makes more sense in the "Expected Behavior".

### Info

<details>

```
### Buffalo Version
v0.13.0

### App Information
Pwd=/home/jonathan/src/github.com/gobuffalo/buffalo
Root=/home/jonathan/src/github.com/gobuffalo/buffalo
GoPath=/home/jonathan
Name=buffalo
Bin=bin/buffalo
PackagePkg=github.com/gobuffalo/buffalo
ActionsPkg=github.com/gobuffalo/buffalo/actions
ModelsPkg=github.com/gobuffalo/buffalo/models
GriftsPkg=github.com/gobuffalo/buffalo/grifts
VCS=git
WithPop=false
WithSQLite=false
WithDep=false
WithWebpack=false
WithYarn=false
WithDocker=true
WithGrifts=true
WithModules=false

### Go Version
go version go1.11.1 linux/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jonathan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jonathan"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build549406355=/tmp/go-build -gno-record-gcc-switches"

### Node Version
v9.11.2

### NPM Version
5.6.0

### Yarn Version
1.10.1

### PostgreSQL Version
pg_ctl (PostgreSQL) 10.5

### MySQL Version
mysql  Ver 15.1 Distrib 10.1.36-MariaDB, for Linux (x86_64) using readline 5.1

### SQLite Version
3.25.2 2018-09-25 19:08:10 fb90e7189ae6d62e77ba3a308ca5d683f90bbe633cf681865365b8e92792d1c7

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

### go.mod
module github.com/gobuffalo/buffalo

require (
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/dustin/go-humanize v1.0.0
	github.com/fatih/color v1.7.0
	github.com/fatih/structs v1.1.0 // indirect
	github.com/gobuffalo/buffalo-plugins v1.0.4
	github.com/gobuffalo/buffalo-pop v1.0.5
	github.com/gobuffalo/envy v1.6.5
	github.com/gobuffalo/events v1.0.7
	github.com/gobuffalo/genny v0.0.0-20181012161047-33e5f43d83a6
	github.com/gobuffalo/github_flavored_markdown v1.0.5
	github.com/gobuffalo/httptest v1.0.2
	github.com/gobuffalo/makr v1.1.5
	github.com/gobuffalo/mw-basicauth v1.0.3
	github.com/gobuffalo/mw-contenttype v0.0.0-20180802152300-74f5a47f4d56
	github.com/gobuffalo/mw-csrf v0.0.0-20180802151833-446ff26e108b
	github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
	github.com/gobuffalo/mw-i18n v0.0.0-20180802152014-e3060b7e13d6
	github.com/gobuffalo/mw-paramlogger v0.0.0-20181005191442-d6ee392ec72e
	github.com/gobuffalo/mw-tokenauth v0.0.0-20181001105134-8545f626c189
	github.com/gobuffalo/packr v1.13.7
	github.com/gobuffalo/plush v3.7.20+incompatible
	github.com/gobuffalo/pop v4.8.4+incompatible
	github.com/gobuffalo/tags v2.0.11+incompatible
	github.com/gobuffalo/x v0.0.0-20181007152206-913e47c59ca7
	github.com/gorilla/context v1.1.1
	github.com/gorilla/mux v1.6.2
	github.com/gorilla/sessions v1.1.3
	github.com/markbates/deplist v1.0.5
	github.com/markbates/grift v1.0.4
	github.com/markbates/inflect v1.0.1
	github.com/markbates/oncer v0.0.0-20181014194634-05fccaae8fc4
	github.com/markbates/refresh v1.4.10
	github.com/markbates/sigtx v1.0.0
	github.com/monoculum/formam v0.0.0-20180901015400-4e68be1d79ba
	github.com/pkg/errors v0.8.0
	github.com/sirupsen/logrus v1.1.1
	github.com/spf13/cobra v0.0.3
	github.com/spf13/pflag v1.0.3
	github.com/spf13/viper v1.2.1
	github.com/stretchr/testify v1.2.2
	github.com/unrolled/secure v0.0.0-20181005190816-ff9db2ff917f // indirect
	golang.org/x/crypto v0.0.0-20181015023909-0c41d7ab0a0e
	golang.org/x/net v0.0.0-20181011144130-49bb7cea24b1 // indirect
	golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
	golang.org/x/sys v0.0.0-20181011152604-fa43e7bc11ba // indirect
	golang.org/x/tools v0.0.0-20181013182035-5e66757b835f
	gopkg.in/mail.v2 v2.0.0-20180731213649-a0242b2233b4
)

```

</details>

**Comment by duckbrain** [comment]
I've already got a MR #1383

**Comment by duckbrain** [comment]
Just saw the comment on the MR.

**Comment by markbates** [comment]
Using this as the reference ticket for the issue. :)

**Comment by markbates** [comment]
Thank you.

**Comment by markbates** [comment]
@duckbrain can you give https://github.com/gobuffalo/buffalo/releases/tag/v0.13.1-rc.1 a whirl and confirm it fixes the issue?

**Comment by duckbrain** [comment]
Confirmed. The issue is fixed.

**Comment by markbates** [comment]
Thanks!
