### ISSUE TITLE
Application crashes (SIGSEGV) when the binary is compiled as static

### ISSUE THREAD

**Issue by sio4** [gobuffalo/buffalo#2149]
### Description

Application crashes (SIGSEGV) when the binary is compiled as static and it needs to resolve DNS name. 

This issue is related to #1597 and #2033 which were not fully addressed before.

### Steps to Reproduce the Problem

  1. buffalo new coke && cd coke
  2. sed -i 's/127.0.0.1/localhost/g' database.yml
  3. buffalo build --static -o coke
  4. ./coke
  5. loading http://localhost:3000

### Expected Behavior

The default welcome page should be shown

### Actual Behavior

Warnings while compilation:

```
/usr/bin/ld: /tmp/go-link-2381281985/000007.o: in function `mygetgrouplist':
/usr/local/go/src/os/user/getgrouplist_unix.go:18: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-2381281985/000006.o: in function `mygetgrgid_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:40: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-2381281985/000006.o: in function `mygetgrnam_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:45: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-2381281985/000006.o: in function `mygetpwnam_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:35: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-2381281985/000006.o: in function `mygetpwuid_r':
/usr/local/go/src/os/user/cgo_lookup_unix.go:30: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-2381281985/000004.o: in function `_cgo_3c1cec0c9a4e_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Error

```
$ ./coke 
INFO[2021-10-06T23:30:54+09:00] Starting application at http://127.0.0.1:3000
INFO[2021-10-06T23:30:54+09:00] Starting Simple Background Worker
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f69103085ca]

runtime stack:
runtime.throw(0xdd82f0, 0x2a)
	/opt/google/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/opt/google/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 41 [syscall]:
runtime.cgocall(0xb9bc40, 0xc000014620, 0xc00048e348)
	/opt/google/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000145f0 sp=0xc0000145b8 pc=0x4056fb
net._C2func_getaddrinfo(0xc0004dc240, 0x0, 0xc0004af170, 0xc00048e348, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:91 +0x50 fp=0xc000014620 sp=0xc0000145f0 pc=0x5cd9b0
net.cgoLookupIPCNAME.func1(0xc0004dc240, 0x11, 0x11, 0xc0004af170, 0xc00048e348, 0x4db271, 0xc0004a22c8, 0x0)
	/opt/google/go/src/net/cgo_unix.go:161 +0xc5 fp=0xc000014668 sp=0xc000014620 pc=0x5d2465
net.cgoLookupIPCNAME(0xdb50d2, 0x2, 0xc0002900bd, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/google/go/src/net/cgo_unix.go:161 +0x16b fp=0xc000014778 sp=0xc000014668 pc=0x5cec2b
net.cgoLookupIP(0x16bddd0, 0xc0000360d8, 0xdb50d2, 0x2, 0xc0002900bd, 0x10, 0xc000014928, 0x5a1468, 0xdc05ff, 0xf, ...)
	/opt/google/go/src/net/cgo_unix.go:224 +0x3a5 fp=0xc0000148a0 sp=0xc000014778 pc=0x5cf7c5
net.cgoLookupHost(0x16bddd0, 0xc0000360d8, 0xc0002900bd, 0x10, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0)
	/opt/google/go/src/net/cgo_unix.go:57 +0x7c fp=0xc000014988 sp=0xc0000148a0 pc=0x5cdc9c
net.(*Resolver).lookupHost(0x1b29700, 0x16bddd0, 0xc0000360d8, 0xc0002900bd, 0x10, 0x0, 0x0, 0x0, 0xdb6d47, 0x8)
	/opt/google/go/src/net/lookup_unix.go:81 +0x14b fp=0xc0000149f0 sp=0xc000014988 pc=0x5bc82b
net.(*Resolver).LookupHost(0x1b29700, 0x16bddd0, 0xc0000360d8, 0xc0002900bd, 0x10, 0x10, 0x10, 0xc9d7a0, 0x0, 0xc000014b30)
	/opt/google/go/src/net/lookup.go:184 +0x1f0 fp=0xc000014a60 sp=0xc0000149f0 pc=0x5bae70
net.(*Resolver).LookupHost-fm(0x16bddd0, 0xc0000360d8, 0xc0002900bd, 0x10, 0xc0004c2740, 0xc000066800, 0x0, 0xc000014b60, 0x4503c5)
	/opt/google/go/src/net/lookup.go:175 +0x65 fp=0xc000014ac0 sp=0xc000014a60 pc=0x878405
github.com/jackc/pgconn.expandWithIPs(0x16bddd0, 0xc0000360d8, 0xc0004b0680, 0xc0004b0890, 0x2, 0x2, 0x1, 0x2, 0xd097c0, 0xc0004c25c0, ...)
	/home/sio4/go/pkg/mod/github.com/jackc/pgconn@v1.8.1/pgconn.go:193 +0x1e7 fp=0xc000014b70 sp=0xc000014ac0 pc=0x86af07
github.com/jackc/pgconn.ConnectConfig(0x16bddd0, 0xc0000360d8, 0xc0004040f0, 0x0, 0x0, 0x0)
	/home/sio4/go/pkg/mod/github.com/jackc/pgconn@v1.8.1/pgconn.go:140 +0x1d9 fp=0xc000014c50 sp=0xc000014b70 pc=0x86a559
github.com/jackc/pgx/v4.connect(0x16bddd0, 0xc0000360d8, 0xc000404000, 0x0, 0x0, 0x408eda)
	/home/sio4/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:222 +0x16b fp=0xc000014cf0 sp=0xc000014c50 pc=0x95668b
github.com/jackc/pgx/v4.ConnectConfig(...)
	/home/sio4/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:113
github.com/jackc/pgx/v4/stdlib.(*driverConnector).Connect(0xc00036e408, 0x16bddd0, 0xc0000360d8, 0xa8f4f7, 0xc0000f2200, 0x16c8920, 0xce4260)
	/home/sio4/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/stdlib/sql.go:223 +0xbb fp=0xc000014d50 sp=0xc000014cf0 pc=0x969afb
database/sql.(*DB).conn(0xc00028dd40, 0x16bddd0, 0xc0000360d8, 0xc00004f001, 0xc000014f30, 0x4bdbdb, 0x4d9148)
	/opt/google/go/src/database/sql/sql.go:1301 +0x184 fp=0xc000014eb8 sp=0xc000014d50 pc=0x7ef244
database/sql.(*DB).begin(0xc00028dd40, 0x16bddd0, 0xc0000360d8, 0x0, 0x40f901, 0xc0004b0620, 0x10, 0x10)
	/opt/google/go/src/database/sql/sql.go:1752 +0x4f fp=0xc000014f18 sp=0xc000014eb8 pc=0x7f320f
database/sql.(*DB).BeginTx(0xc00028dd40, 0x16bddd0, 0xc0000360d8, 0x0, 0xc000014fe8, 0x410078, 0x10)
	/opt/google/go/src/database/sql/sql.go:1734 +0x8f fp=0xc000014f98 sp=0xc000014f18 pc=0x7f2fcf
github.com/jmoiron/sqlx.(*DB).BeginTxx(0xc000304300, 0x16bddd0, 0xc0000360d8, 0x0, 0xc22246e451f75d55, 0xd83c60, 0xce6ea0)
	/home/sio4/go/pkg/mod/github.com/jmoiron/sqlx@v1.3.3/sqlx_context.go:204 +0x50 fp=0xc000014ff8 sp=0xc000014f98 pc=0x980ed0
github.com/gobuffalo/pop/v5.newTX(0x16bddd0, 0xc0000360d8, 0xc000376138, 0x0, 0xd82080, 0x7600000000b5ebc5, 0xc0000150c0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/tx.go:27 +0x85 fp=0xc000015050 sp=0xc000014ff8 pc=0xac7c85
github.com/gobuffalo/pop/v5.(*dB).Transaction(0xc000376138, 0x40441a, 0xcb8e20, 0x416dbb)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/db.go:19 +0x4c fp=0xc000015098 sp=0xc000015050 pc=0xaa722c
github.com/gobuffalo/pop/v5.(*Connection).NewTransaction(0xc00008c3c0, 0x18, 0xd29340, 0xc0000151c0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/connection.go:184 +0x62 fp=0xc000015120 sp=0xc000015098 pc=0xaa5382
github.com/gobuffalo/pop/v5.(*Connection).Transaction.func1(0xc000066800, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/connection.go:149 +0x37 fp=0xc000015180 sp=0xc000015120 pc=0xac8f77
github.com/gobuffalo/pop/v5.commonDialect.Lock(0xc0002aa000, 0xc00000e330, 0xc000066801, 0xc00000e330)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/dialect_common.go:29 +0x27 fp=0xc0000151a0 sp=0xc000015180 pc=0xaaab47
github.com/gobuffalo/pop/v5.(*postgresql).Lock(0xc00036e048, 0xc00000e330, 0x1, 0xc0004e8360)
	<autogenerated>:1 +0x45 fp=0xc0000151d0 sp=0xc0000151a0 pc=0xad1a45
github.com/gobuffalo/pop/v5.(*Connection).Transaction(0xc00008c3c0, 0xc0004e8360, 0x3, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/connection.go:147 +0x72 fp=0xc000015200 sp=0xc0000151d0 pc=0xaa5212
github.com/gobuffalo/buffalo-pop/v2/pop/popmw.Transaction.func2.1(0x16c7578, 0xc0004e6770, 0x4, 0xc0004ac040)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo-pop/v2@v2.3.0/pop/popmw/tx.go:40 +0x8f fp=0xc000015250 sp=0xc000015200 pc=0xb60d4f
github.com/gobuffalo/mw-csrf.glob..func1.1(0x16c7578, 0xc0004e6770, 0xc0004aea80, 0x16b8460)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/mw-csrf@v1.0.0/csrf.go:122 +0x431 fp=0xc000015310 sp=0xc000015250 pc=0xb61991
github.com/gobuffalo/mw-paramlogger.parameterLogger.Middleware.func1(0x16c7578, 0xc0004e6770, 0x0, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/mw-paramlogger@v1.0.0/param_logger.go:63 +0x98 fp=0xc000015380 sp=0xc000015310 pc=0xb60178
github.com/gobuffalo/mw-forcessl.Middleware.func1.1(0x16c7578, 0xc0004e6770, 0xc000015418, 0x4caee6)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/mw-forcessl@v0.0.0-20200131175327-94b2bd771862/forcessl.go:26 +0x109 fp=0xc0000153e0 sp=0xc000015380 pc=0xb5ee69
github.com/gobuffalo/buffalo.sessionSaver.func1(0x16c7578, 0xc0004e6770, 0x1b2a320, 0xcb8e20)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/session.go:69 +0x3d fp=0xc000015428 sp=0xc0000153e0 pc=0xb5a11d
github.com/gobuffalo/buffalo.RequestLoggerFunc.func1(0x16c7578, 0xc0004e6770, 0x0, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/request_logger.go:74 +0x2aa fp=0xc0000154f8 sp=0xc000015428 pc=0xb5868a
github.com/gobuffalo/buffalo.(*App).PanicHandler.func1(0x16c7578, 0xc0004e6770, 0x0, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/errors.go:97 +0x7e fp=0xc000015550 sp=0xc0000154f8 pc=0xb5631e
github.com/gobuffalo/buffalo.(*App).defaultErrorMiddleware.func1(0x16c7578, 0xc0004e6770, 0x3, 0x1ae0638)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/errors.go:103 +0x62 fp=0xc000015680 sp=0xc000015550 pc=0xb563e2
github.com/gobuffalo/buffalo.RouteInfo.ServeHTTP(0xdb54fe, 0x3, 0x1ae0638, 0x1, 0x17b1146, 0x18, 0x0, 0x0, 0xc00028b288, 0x8, ...)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/route_info.go:104 +0x323 fp=0xc000015828 sp=0xc000015680 pc=0xb50563
github.com/gobuffalo/buffalo.(*RouteInfo).ServeHTTP(0xc0003c0600, 0x16b8460, 0xc0004e8000, 0xc0004cc200)
	<autogenerated>:1 +0xc8 fp=0xc000015950 sp=0xc000015828 pc=0xb5ac28
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002c4300, 0x16b8460, 0xc0004e8000, 0xc0004cc000)
	/home/sio4/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3 fp=0xc000015a88 sp=0xc000015950 pc=0xada953
github.com/markbates/refresh/refresh/web.ErrorChecker.func1(0x16b8460, 0xc0004e8000, 0xc0004cc000)
	/home/sio4/go/pkg/mod/github.com/markbates/refresh@v1.11.1/refresh/web/web.go:23 +0x97 fp=0xc000015af8 sp=0xc000015a88 pc=0xb43df7
net/http.HandlerFunc.ServeHTTP(0xc00000e048, 0x16b8460, 0xc0004e8000, 0xc0004cc000)
	/opt/google/go/src/net/http/server.go:2049 +0x44 fp=0xc000015b20 sp=0xc000015af8 pc=0x6c0924
github.com/gobuffalo/buffalo.(*App).ServeHTTP(0xc0002dc680, 0x16ba650, 0xc0004e0000, 0xc0004cc000)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/server.go:134 +0x171 fp=0xc000015b70 sp=0xc000015b20 pc=0xb54cb1
net/http.serverHandler.ServeHTTP(0xc0002e4380, 0x16ba650, 0xc0004e0000, 0xc0004cc000)
	/opt/google/go/src/net/http/server.go:2867 +0xa3 fp=0xc000015ba0 sp=0xc000015b70 pc=0x6c3fe3
net/http.(*conn).serve(0xc0004c8000, 0x16bde40, 0xc0004c2040)
	/opt/google/go/src/net/http/server.go:1932 +0x8cd fp=0xc000015fc8 sp=0xc000015ba0 pc=0x6bf40d
runtime.goexit()
	/opt/google/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000015fd0 sp=0xc000015fc8 pc=0x46e961
created by net/http.(*Server).Serve
	/opt/google/go/src/net/http/server.go:2993 +0x39b

goroutine 1 [chan receive]:
github.com/gobuffalo/buffalo.(*App).Serve(0xc0002dc680, 0xc00030d240, 0x1, 0x1, 0x0, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/server.go:95 +0x4d9
main.originalMain()
	/home/sio4/git/hyeoncheon/coke/main.go:17 +0x3c
main.main()
	/home/sio4/git/hyeoncheon/coke/buffalo_build_main.go:49 +0xb9

goroutine 51 [select]:
database/sql.(*DB).connectionOpener(0xc00028dd40, 0x16bdd98, 0xc000284540)
	/opt/google/go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
	/opt/google/go/src/database/sql/sql.go:740 +0x12a

goroutine 54 [syscall]:
os/signal.signal_recv(0x0)
	/opt/google/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	/opt/google/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/opt/google/go/src/os/signal/signal.go:151 +0x45

goroutine 37 [select]:
github.com/markbates/sigtx.WithCancel.func1(0xc00008d4a0, 0xc00030d250, 0x16bdd98, 0xc000284800)
	/home/sio4/go/pkg/mod/github.com/markbates/sigtx@v1.0.0/context.go:14 +0x87
created by github.com/markbates/sigtx.WithCancel
	/home/sio4/go/pkg/mod/github.com/markbates/sigtx@v1.0.0/context.go:13 +0xe5

goroutine 38 [chan receive]:
github.com/gobuffalo/buffalo.(*App).Serve.func1(0x16bdd98, 0xc000284800, 0xc0002dc680, 0xc00032e9c0, 0xc00030d240, 0x1, 0x1)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/server.go:48 +0x52
created by github.com/gobuffalo/buffalo.(*App).Serve
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/server.go:46 +0x3b1

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x7f69105a77d8, 0x72, 0x0)
	/opt/google/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000f2018, 0x72, 0x0, 0x0, 0xdb953f)
	/opt/google/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/google/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000f2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/google/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0000f2000, 0x6dd71325c87c7701, 0x0, 0x0)
	/opt/google/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00000e030, 0x615db323, 0xc000070d90, 0x4caee6)
	/opt/google/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000e030, 0xc000070de0, 0x18, 0xc000480c00, 0x6c44db)
	/opt/google/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc0002e4380, 0x16ba470, 0xc00000e030, 0x0, 0x0)
	/opt/google/go/src/net/http/server.go:2961 +0x285
net/http.(*Server).ListenAndServe(0xc0002e4380, 0x0, 0x0)
	/opt/google/go/src/net/http/server.go:2890 +0xba
github.com/gobuffalo/buffalo/servers.(*Simple).Start(0xc000376240, 0x16bdd98, 0xc000284800, 0x16abbe0, 0xc0002dc680, 0x0, 0x0)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/servers/simple.go:23 +0x4e
github.com/gobuffalo/buffalo.(*App).Serve.func3(0x16bdd98, 0xc000284800, 0xc0002dc680, 0x16b84c0, 0xc000376240)
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/server.go:89 +0x5f
created by github.com/gobuffalo/buffalo.(*App).Serve
	/home/sio4/go/pkg/mod/github.com/gobuffalo/buffalo@v0.17.3/server.go:88 +0x487

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x7f69105a76f0, 0x72, 0xffffffffffffffff)
	/opt/google/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000f2118, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/opt/google/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/google/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f2100, 0xc0004ae281, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/google/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000f2100, 0xc0004ae281, 0x1, 0x1, 0x0, 0x0, 0xc00049ff60)
	/opt/google/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00048e018, 0xc0004ae281, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/google/go/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc0004ae270)
	/opt/google/go/src/net/http/server.go:672 +0x58
created by net/http.(*connReader).startBackgroundRead
	/opt/google/go/src/net/http/server.go:668 +0xd5
```

### Info

OS: Ubuntu 20.04.3 LTS
Arch: x86_64

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /opt/google/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.16.7, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /home/sio4/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v14.17.6, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.15, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.11, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✓ The `mysql` executable was found on your system at: /usr/bin/mysql

-> MySQL: Checking minimum version requirements
✓ Your version of MySQL, 8.0.26, meets the minimum requirements.

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.31.1, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /home/sio4/go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.17.5, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/sio4/git/hyeoncheon/coke
Root        /home/sio4/git/hyeoncheon/coke
GoPath      /home/sio4/go
PackagePkg  coke
ActionsPkg  coke/actions
ModelsPkg   coke/models
GriftsPkg   coke/grifts
WithModules true
Name        coke
Bin         bin/coke
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack --mode production --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "coke"
bin = "bin/coke"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v2"

-> Buffalo: go.mod
module coke

go 1.16

require (
	github.com/gobuffalo/buffalo v0.17.3
	github.com/gobuffalo/buffalo-pop/v2 v2.3.0
	github.com/gobuffalo/envy v1.9.0
	github.com/gobuffalo/mw-csrf v1.0.0
	github.com/gobuffalo/mw-forcessl v0.0.0-20200131175327-94b2bd771862
	github.com/gobuffalo/mw-i18n v1.1.0
	github.com/gobuffalo/mw-paramlogger v1.0.0
	github.com/gobuffalo/packr/v2 v2.8.1
	github.com/gobuffalo/pop/v5 v5.3.4
	github.com/gobuffalo/suite v2.8.2+incompatible
	github.com/markbates/grift v1.5.0
	github.com/unrolled/secure v1.0.9
)
```

</details>

**Comment by fasmat** [comment]
I ran into this as well. The reason afaik isn't something related to buffalo, but how static go builds in general have issues when running on Ubuntu.

A fix that works for me is to add a tag to the build, that instructs go to use the netgo network stack instead of the ubuntu one:

`buffalo build --static --tags netgo -o bin/app`

You still get build warnings but the app doesn't crash any more.
If i build my source on e.g. alpine I have no issues.
