### ISSUE TITLE
v0.7.3 webpack2.0 release breaks default configuration

### ISSUE THREAD

**Issue by charlesmims** [gobuffalo/buffalo#262]
With a fresh install of v0.7.3 and go v1.8, using postres, I get the following error when trying to start `buffalo dev` on a new project:

```
cmims@MBP:~/go/src/github.com/charlesmims/buffalo-blog$ buffalo dev
Buffalo version 0.7.3

buffalo: 2017/02/26 13:54:39 === Rebuild on: :start: ===
buffalo: 2017/02/26 13:54:39 === Running: go build -v -i -o tmp/buffalo-blog-build (PID: 14209) ===
/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/extract-text-webpack-plugin/index.js:176
		throw new Error("Breaking change: extract now only takes a single argument. Either an options " +
		^

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })

The available options are:
    use: string | object | loader[]
    fallback: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/extract-text-webpack-plugin/index.js:176:9)
    at Object.<anonymous> (/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/webpack.config.js:38:33)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
2017/02/26 13:54:40 exit status 1
```

I modified webpack.config.js so that lines 38-41 changed from 
```
      loader: ExtractTextPlugin.extract(
        "style",
        "css?sourceMap!sass?sourceMap"
      )
```
to 
```
      loader: ExtractTextPlugin.extract(
        {
          fallback: "style",
          use: "css?sourceMap!sass?sourceMap"
        }
      )
```
and now I get
```
cmims@MBP:~/go/src/github.com/charlesmims/buffalo-blog$ buffalo dev
Buffalo version 0.7.3

buffalo: 2017/02/26 13:27:29 === Rebuild on: :start: ===
buffalo: 2017/02/26 13:27:29 === Running: go build -v -i -o tmp/buffalo-blog-build (PID: 13605) ===
/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/webpack-core/lib/LoadersList.js:58
	if(element.loader) return element.loader.split("!");
	                                         ^

TypeError: element.loader.split is not a function
```

I manually upgraded npm  and node (was on 7.5.0, now 7.6.0) and installed webpack@2.2.1.  Now it runs,  with the following errors:
```
ERROR in ./assets/js/application.js
Module build failed: Error: The node API for `babel` has been moved to `babel-core`.
...
ERROR in multi ./assets/js/application.js ./assets/css/application.scss ./~/jquery-ujs/src/rails.js
Module not found: Error: Can't resolve 'css?sourceMap' in '/Users/cmims/go/src/github.com/charlesmims/buffalo-blog'
...
ERROR in ./~/jquery-ujs/src/rails.js
Module not found: Error: Can't resolve 'expose' in '/Users/cmims/go/src/github.com/charlesmims/buffalo-blog'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
...
```
Installing webpack@2.2.1 said it was invalid. 
I tried running `npm update; npm upgrade` and now I'm back to the error message 
```
Buffalo version 0.7.3

buffalo: 2017/02/26 14:12:23 === Rebuild on: :start: ===
buffalo: 2017/02/26 14:12:23 === Running: go build -v -i -o tmp/buffalo-blog-build (PID: 15479) ===
/Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/webpack-core/lib/LoadersList.js:58
	if(element.loader) return element.loader.split("!");
	                                         ^

TypeError: element.loader.split is not a function
```

**Comment by charlesmims** [comment]
```
cmims@MBP:~/go/src/github.com/charlesmims/buffalo-blog$ npm list | grep webpack
├─┬ copy-webpack-plugin@4.0.1
├─┬ extract-text-webpack-plugin@2.0.0
├─┬ npm-install-webpack-plugin@4.0.4
└─┬ webpack@2.2.1 invalid
  ├── webpack-sources@0.1.4
npm ERR! invalid: webpack@2.2.1 /Users/cmims/go/src/github.com/charlesmims/buffalo-blog/node_modules/webpack
```

**Comment by charlesmims** [comment]
Amós Oviedo figured out that setting     "extract-text-webpack-plugin": "~0.8.0",  in package.json clears this up.
