### ISSUE TITLE
buffalo command throwing errors

### ISSUE THREAD

**Issue by fadeojo** [gobuffalo/buffalo#266]
I ran `go get -u github.com/gobuffalo/buffalo/buffalo`
 and any `buffalo` command I run shows the following;
```
╰─○ buffalo help
panic: [POP]: Tried to load configuration file, but couldn't find it.

goroutine 1 [running]:
panic(0x46bbb80, 0xc420246d60)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/markbates/pop/soda/cmd.init.9()
	/Users/fadeojo/golang/src/github.com/markbates/pop/soda/cmd/root.go:50 +0x259
github.com/markbates/pop/soda/cmd.init()
	/Users/fadeojo/golang/src/github.com/markbates/pop/soda/cmd/version.go:4 +0x79
github.com/gobuffalo/buffalo/buffalo/cmd.init()
	/Users/fadeojo/golang/src/github.com/gobuffalo/buffalo/buffalo/cmd/version.go:5 +0x87
main.init()
	/Users/fadeojo/golang/src/github.com/gobuffalo/buffalo/buffalo/main.go:8 +0x2e
```

go version: `go version go1.7.4 darwin/amd64`

**Comment by fooflare** [comment]
This issue is caused by pop, I just opened there another one to solve this.

**Comment by markbates** [comment]
I've rolled back those commits to pop, so this should be resolved now.
