### ISSUE TITLE
node deprecation warning for loader-utils

### ISSUE THREAD

**Issue by markbates** [gobuffalo/buffalo#369]
```
(node:98894) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/babel-loader/lib/index.js:104:35)
    at LOADER_EXECUTION (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/markbates/Dropbox/development/gocode/src/github.com/markbates/coke/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

**Comment by markbates** [comment]
Apparently this will be resolved on it's own in the next version of the `babel-loader`. https://github.com/babel/babel-loader/issues/392

Nothing to be done here.
