### ISSUE TITLE
New project tests fail (on buffalo 0.9.0)

### ISSUE THREAD

**Issue by alexcarol** [gobuffalo/buffalo#489]
Steps to reproduce:
buffalo new test --db-type mysql
buffalo test

Result:
```
➜  test go test github.com/alexcarol/test github.com/alexcarol/test/actions github.com/alexcarol/test/grifts github.com/alexcarol/test/models     

?       github.com/alexcarol/test       [no test files]
[POP] 2017/07/03 21:33:39 SELECT concat('TRUNCATE TABLE `', TABLE_NAME, '`;') as stmt FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = ? | ["test_test"]
--- FAIL: Test_HomeHandler (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x982238]

goroutine 11 [running]:
testing.tRunner.func1(0xc420234d00)
        /usr/local/go/src/testing/testing.go:622 +0x29d
panic(0xb22ee0, 0x1129040)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*Model).TableName(0x0, 0x0, 0x0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/model.go:115 +0x38
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*sqlBuilder).buildColumns(0xc42048e000, 0x0, 0x0, 0x0, 0x0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/sql_builder.go:156 +0x47
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*sqlBuilder).buildSelectSQL(0xc42048e000, 0x0, 0x0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/sql_builder.go:66 +0x40
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*sqlBuilder).compile(0xc42048e000)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/sql_builder.go:52 +0x29b
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*sqlBuilder).String(0xc42048e000, 0x0, 0x0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/sql_builder.go:31 +0x59
github.com/alexcarol/test/vendor/github.com/markbates/pop.Query.ToSQL(0xc420484120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/query.go:93 +0xb9
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*Query).Exec.func1(0xed0ec9313, 0x2d04fc33)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/executors.go:18 +0x96
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*Connection).timeFunc(0xc420214ac0, 0xbcb700, 0x4, 0xc420183d78, 0x0, 0x0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/connection.go:175 +0x51
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*Query).Exec(0xc42048c000, 0x0, 0x0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/executors.go:22 +0x6b
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*mysql).TruncateAll(0xc42000e950, 0xc420214ac0, 0xb1dd01, 0xc420231eb0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/mysql.go:154 +0x309
github.com/alexcarol/test/vendor/github.com/markbates/pop.(*Connection).TruncateAll(0xc420214ac0, 0xc420231eb0, 0xb5aa20)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/markbates/pop/connection.go:170 +0x3c
github.com/alexcarol/test/vendor/github.com/gobuffalo/suite.(*Model).SetupTest(0xc420233020)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/gobuffalo/suite/model.go:19 +0x9d
github.com/alexcarol/test/vendor/github.com/gobuffalo/suite.(*Action).SetupTest(0xc4202330e0)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/gobuffalo/suite/suite.go:47 +0x160
github.com/alexcarol/test/vendor/github.com/stretchr/testify/suite.Run.func2(0xc420234d00)
        /home/alex/go/src/github.com/alexcarol/test/vendor/github.com/stretchr/testify/suite/suite.go:87 +0x1b2
testing.tRunner(0xc420234d00, 0xc4203f0690)
        /usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:697 +0x2ca
FAIL    github.com/alexcarol/test/actions       0.012s
?       github.com/alexcarol/test/grifts        [no test files]
ok      github.com/alexcarol/test/models        0.007s [no tests to run]

```
It looks like the issue is originated in markbates/pop executors.go file, where nil is passed to q.ToSQL, but i'm not sure how to address it.
```

func (q *Query) Exec() error {
	return q.Connection.timeFunc("Exec", func() error {
		sql, args := q.ToSQL(nil)
		Log(sql, args...)
		_, err := q.Connection.Store.Exec(sql, args...)
		return err
	})
}

```

Thanks!

**Comment by markbates** [comment]
I'm unable to reproduce this.

```
$ buffalo new test --db-type mysql
$ buffalo test

Buffalo version v0.9.0

dropped database test_test
created database test_test
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got error: 1049: Unknown database 'test_development' when selecting the database

0.3187 seconds
go test -p 1 github.com/markbates/test github.com/markbates/test/actions github.com/markbates/test/grifts github.com/markbates/test/models
?   	github.com/markbates/test	[no test files]
ok  	github.com/markbates/test/actions	0.061s
?   	github.com/markbates/test/grifts	[no test files]
ok  	github.com/markbates/test/models	0.030s [no tests to run]
```

Is there anything else you're leaving out that could help me reproduce? Any steps you forgot to mention? What version of Go are you using? What does your `Gopkg.lock` file look like (if you have one). What OS are you on? Version of MySQL, etc...

**Comment by alexcarol** [comment]
Your commit actually fixes my issue, thanks for your super quick response!
The only step I skipped is changing the user and password from root:root to alex:alex in the database.yml. 

To respond to your question about environment:
mysql (mariadb) version: ``` mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 ```
OS: ```Linux galactica 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux```
Gopkg.lock: https://gist.github.com/alexcarol/28d13ef989a668fd7d1c22b859a1deb3

**Comment by markbates** [comment]
Glad it fixed it. It must be because of Maria vs. MySQL.
