### ISSUE TITLE
webpack error in Buffalo 0.9.1.2

### ISSUE THREAD

**Issue by bscott** [gobuffalo/buffalo#532]
Generated a brand new app and receiving the following error:

```
--> cleaning up target dir
--> running node_modules/.bin/webpack -p
/go/src/github.com/bscott/test/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
 
--> cleaning up build
----> cleaning up buffalo_build_main.go
Usage:
  buffalo build [flags]

Aliases:
  build, b, bill

Flags:
  -e, --extract-assets   extract the assets and put them in a distinct archive
  -h, --help             help for build
      --ldflags string   set any ldflags to be passed to the go build
  -o, --output string    set the name of the binary (default "bin/petsglobalportal")
  -s, --static           build a static binary using  --ldflags '-linkmode external -extldflags "-static"' (USE FOR CGO)
  -t, --tags string      compile with specific build tags

Error: exit status 1

The command '/bin/sh -c buffalo build --static -o /bin/app' returned a non-zero code: 255
 ▸    Error: docker build exited with 255
Error: exit status 1
Usage:
  buffalo-heroku heroku deploy [flags]

Aliases:
  deploy, d

Flags:
  -h, --help   help for deploy

exit status 1
Usage:
  buffalo heroku [flags]

Flags:
  -h, --help   help for heroku

Error: exit status 1

```

**Comment by markbates** [comment]
Are you sure you're running `0.9.1.2`? This was fixed in `0.9.1.1` here: https://github.com/gobuffalo/buffalo/commit/6b232913aabfed10b409187c74f1d71ea33168d0

You should have `extract-text-webpack-plugin` pinned to `2.1.2` in `package.json`.

**Comment by apaganobeleno** [comment]
@bscott does this one still happens to you ?

**Comment by bscott** [comment]
@apaganobeleno I'm going to check

**Comment by bscott** [comment]
Seems to be fixed with this. 

You should have extract-text-webpack-plugin pinned to 2.1.2 in package.json.

**Comment by Coccoonx** [comment]
Hello,
I'm facing the same issue with new generate application. I have version 3.0.0 of extract-text-webpack-plugin.
Here is the entire log:

```
Buffalo version v0.9.0

buffalo: 2017/08/01 12:24:53 === Rebuild on: :start: ===
buffalo: 2017/08/01 12:24:53 === Running: go build -v -i -o tmp/coke-build  (PID: 19289) ===

Webpack is watching the files…

/home/bonways/go/src/github.com/bonways/coke/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
    at /home/bonways/go/src/github.com/bonways/coke/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /home/bonways/go/src/github.com/bonways/coke/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/home/bonways/go/src/github.com/bonways/coke/node_modules/async/dist/async.js:1003:9)
    at eachOf (/home/bonways/go/src/github.com/bonways/coke/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/home/bonways/go/src/github.com/bonways/coke/node_modules/async/dist/async.js:3145:5)
    at Compilation.<anonymous> (/home/bonways/go/src/github.com/bonways/coke/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/home/bonways/go/src/github.com/bonways/coke/node_modules/tapable/lib/Tapable.js:188:13)
    at Compilation.seal (/home/bonways/go/src/github.com/bonways/coke/node_modules/webpack/lib/Compilation.js:579:8)
    at /home/bonways/go/src/github.com/bonways/coke/node_modules/webpack/lib/Compiler.js:493:16
    at /home/bonways/go/src/github.com/bonways/coke/node_modules/tapable/lib/Tapable.js:271:11
    at _addModuleChain (/home/bonways/go/src/github.com/bonways/coke/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/home/bonways/go/src/github.com/bonways/coke/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
github.com/bonways/coke
2017/08/01 12:25:15 exit status 1
```

**Comment by markbates** [comment]
This was fixed in version 0.9.1.1. If you upgrade Buffalo, current version is 0.9.2, and regenerate it'll pin the version to 0f that node module to 2.1.2. 

Alternatively you could pin it in your package.json.

**Comment by Coccoonx** [comment]
I just upgrade Buffalo to 0.9.2 and try creation of new application. But I have this error:
`Error: exec: "dep": executable file not found in $PATH`
How can I fix this ?

**Comment by markbates** [comment]
Sorry, the dep team changed their install path recently. 

go install github.com/golang/dep/cmd/dep

Alternatively I would recommend generating new apps with --skip-dep

**Comment by Coccoonx** [comment]
Ok. Working now.
Thanks
