### ISSUE TITLE
concurrent hashmap write issue

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#697]
buffalo 0.9.5 golang 1.9

on development, encounter this on buffalo dev:
```
goroutine 23 [running]:
runtime.throw(0x4c0850f, 0x15)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:605 +0x95 fp=0xc420673590 sp=0xc420673570 pc=0x402d005
runtime.mapassign_fast64(0x4af83c0, 0xc42022abd0, 0x476dc60, 0x528c8e0)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/hashmap_fast.go:592 +0x3b7 fp=0xc4206735f0 sp=0xc420673590 pc=0x400f5f7
project/vendor/github.com/gobuffalo/buffalo.funcKey(0xc4206738e0, 0x2, 0x2, 0xc420448e00, 0xc420770bf0)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/middleware.go:147 +0x418 fp=0xc420673838 sp=0xc4206735f0 pc=0x45817e8
project/vendor/github.com/gobuffalo/buffalo.(*MiddlewareStack).handler(0xc4205d06e0, 0x4bf231c, 0x3, 0xc4205c4ce0, 0x16, 0xc42058be30, 0x24, 0xc4205d73a0, 0xc, 0x528bce8, ...)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/middleware.go:112 +0x221 fp=0xc420673980 sp=0xc420673838 pc=0x4581081
project/vendor/github.com/gobuffalo/buffalo.RouteInfo.ServeHTTP(0x4bf231c, 0x3, 0xc4205c4ce0, 0x16, 0xc42058be30, 0x24, 0xc4205d73a0, 0xc, 0x528bce8, 0x0, ...)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/handler.go:75 +0x193 fp=0xc420673a88 sp=0xc420673980 pc=0x457e723
project/vendor/github.com/gobuffalo/buffalo.(*RouteInfo).ServeHTTP(0xc4205e28c0, 0x5217800, 0xc4207ec7e0, 0xc420879300)
	<autogenerated>:1 +0x8a fp=0xc420673b20 sp=0xc420673a88 pc=0x45899ea
project/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420237bc0, 0x5217800, 0xc4207ec7e0, 0xc420879300)
	/Users/james/www/gowork/src/project/vendor/github.com/gorilla/mux/mux.go:133 +0xed fp=0xc420673c20 sp=0xc420673b20 pc=0x42d5bfd
project/vendor/github.com/markbates/refresh/refresh/web.ErrorChecker.func1(0x5217800, 0xc4207ec7e0, 0xc4207f0300)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/refresh/refresh/web/web.go:23 +0xb1 fp=0xc420673cb0 sp=0xc420673c20 pc=0x435df11
net/http.HandlerFunc.ServeHTTP(0xc4207ec800, 0x5217800, 0xc4207ec7e0, 0xc4207f0300)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1918 +0x44 fp=0xc420673cd8 sp=0xc420673cb0 pc=0x4288304
project/vendor/github.com/gobuffalo/buffalo.(*App).ServeHTTP(0xc4202dc8c0, 0x52176c0, 0xc4207de1c0, 0xc4207f0300)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/app.go:120 +0x116 fp=0xc420673d18 sp=0xc420673cd8 pc=0x457a266
net/http.serverHandler.ServeHTTP(0xc420078000, 0x52176c0, 0xc4207de1c0, 0xc4207f0300)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2619 +0xb4 fp=0xc420673d48 sp=0xc420673d18 pc=0x428af64
net/http.(*conn).serve(0xc4204712c0, 0x5219ac0, 0xc4203b8580)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1801 +0x71d fp=0xc420673fc8 sp=0xc420673d48 pc=0x42871dd
runtime.goexit()
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420673fd0 sp=0xc420673fc8 pc=0x405af21
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2720 +0x288

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x5a08f70, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42011c018, 0x72, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.1/libexec/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42011c018, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.1/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42011c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.1/libexec/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc42011c000, 0x40147b9, 0xc420471b60, 0x4ae1680)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e7b8, 0x4ae1680, 0xc420641ce8, 0x40032a7)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000e7b8, 0xc420641d30, 0xc420641d38, 0xc420641d28)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000e7b8, 0x4c53340, 0xc420471ae0, 0x5219b80, 0xc42050d7a0)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc420078000, 0x5219380, 0xc42000e7b8, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc420078000, 0xc420078000, 0x0)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2636 +0xa9
net/http.ListenAndServe(0xc4202c8948, 0x5, 0x520e3c0, 0xc4202dc8c0, 0x1, 0xc4202c8948)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2882 +0x7f
main.startServer()
	/Users/james/www/gowork/src/project/main.go:29 +0x1d7
main.main()
	/Users/james/www/gowork/src/project/main.go:36 +0x184

goroutine 50 [runnable]:
project/vendor/github.com/jmoiron/sqlx.(*DB).Beginx(0xc42022be30, 0xc420774210, 0x5a87de0, 0x4055240)
	/Users/james/www/gowork/src/project/vendor/github.com/jmoiron/sqlx/sqlx.go:334 +0x15a
project/vendor/github.com/markbates/pop.newTX(0xc42000ee40, 0x1280005a1a160, 0x150, 0x150)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/pop/tx.go:24 +0x62
project/vendor/github.com/markbates/pop.(*dB).Transaction(0xc42000ee40, 0x4013627, 0xc42076c2c0, 0x20)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/pop/db.go:10 +0x2b
project/vendor/github.com/markbates/pop.(*Connection).NewTransaction(0xc420234140, 0xc420012a80, 0x566a000, 0x0)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/pop/connection.go:126 +0x65
project/vendor/github.com/markbates/pop.(*Connection).Transaction.func1(0xc42066f701, 0xc42076c2c0)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/pop/connection.go:105 +0x37
project/vendor/github.com/markbates/pop.(*postgresql).Lock(0xc4201e3080, 0xc42076c2c0, 0x20, 0x4b44100)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/pop/postgresql.go:170 +0x27
project/vendor/github.com/markbates/pop.(*Connection).Transaction(0xc420234140, 0xc42076c280, 0xc42069c0a0, 0xc42066f850)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/pop/connection.go:103 +0x7d
project/vendor/github.com/gobuffalo/buffalo/middleware.glob..func2.1.1(0x5221080, 0xc420452b60, 0x16, 0x4bf7377)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:22 +0x96
project/middleware.FormatMiddleware.func1(0x5221080, 0xc420452b60, 0xc4202dc8c0, 0x5221080)
	/Users/james/www/gowork/src/project/middleware/format.go:48 +0x5f0
project/vendor/github.com/gobuffalo/buffalo.(*App).PanicHandler.func1(0x5221080, 0xc420452b60, 0x0, 0x0)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/errors.go:69 +0x92
project/vendor/github.com/gobuffalo/buffalo.RouteInfo.ServeHTTP(0x4bf231c, 0x3, 0xc4203e4fe0, 0x14, 0xc4203fc030, 0x27, 0xc4203f8590, 0x10, 0x528bce8, 0x0, ...)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/handler.go:75 +0x1b6
project/vendor/github.com/gobuffalo/buffalo.(*RouteInfo).ServeHTTP(0xc4203f6850, 0x5217800, 0xc420898000, 0xc420700200)
	<autogenerated>:1 +0x8a
project/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420237bc0, 0x5217800, 0xc420898000, 0xc420700200)
	/Users/james/www/gowork/src/project/vendor/github.com/gorilla/mux/mux.go:133 +0xed
project/vendor/github.com/markbates/refresh/refresh/web.ErrorChecker.func1(0x5217800, 0xc420898000, 0xc420121400)
	/Users/james/www/gowork/src/project/vendor/github.com/markbates/refresh/refresh/web/web.go:23 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc420898020, 0x5217800, 0xc420898000, 0xc420121400)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1918 +0x44
project/vendor/github.com/gobuffalo/buffalo.(*App).ServeHTTP(0xc4202dc8c0, 0x52176c0, 0xc420892000, 0xc420121400)
	/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/app.go:120 +0x116
net/http.serverHandler.ServeHTTP(0xc420078000, 0x52176c0, 0xc420892000, 0xc420121400)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4205440a0, 0x5219ac0, 0xc4202340c0)
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2720 +0x288
...
```

**Comment by stanislas-m** [comment]
@u007 `keyMap` from the middleware is not protected against concurrent access. This should have a mutex, like in your similar issue in POP.

**Comment by stanislas-m** [comment]
@u007, can you try this fix? https://github.com/gobuffalo/buffalo/pull/699
