### ISSUE TITLE
concurrent hashmap write issue

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#758]
hi,

one more concurrent hashmap issue:
```

fatal error: concurrent map writes

goroutine 135 [running]:
runtime.throw(0x4c2723d, 0x15)
/usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:605 +0x95 fp=0xc4207db590 sp=0xc4207db570 pc=0x402cad5
runtime.mapassign_fast64(0x4b14e20, 0xc420242960, 0x47757a0, 0x52d0c60)
/usr/local/Cellar/go/1.9.1/libexec/src/runtime/hashmap_fast.go:592 +0x3b7 fp=0xc4207db5f0 sp=0xc4207db590 pc=0x400f0c7
project/vendor/github.com/gobuffalo/buffalo.funcKey(0xc4207db8e0, 0x2, 0x2, 0xc4204969a0, 0xc4208d7a50)
/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/middleware.go:147 +0x418 fp=0xc4207db838 sp=0xc4207db5f0 pc=0x45818b8
project/vendor/github.com/gobuffalo/buffalo.(*MiddlewareStack).handler(0xc4206450c0, 0x4c10bbe, 0x3, 0xc42063bbe0, 0xf, 0xc42061f4a0, 0x27, 0xc42063bcc0, 0x11, 0x52d0068, ...)
/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/middleware.go:112 +0x221 fp=0xc4207db980 sp=0xc4207db838 pc=0x4581151
project/vendor/github.com/gobuffalo/buffalo.RouteInfo.ServeHTTP(0x4c10bbe, 0x3, 0xc42063bbe0, 0xf, 0xc42061f4a0, 0x27, 0xc42063bcc0, 0x11, 0x52d0068, 0x0, ...)
/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/handler.go:75 +0x193 fp=0xc4207dba88 sp=0xc4207db980 pc=0x457e7f3
project/vendor/github.com/gobuffalo/buffalo.(*RouteInfo).ServeHTTP(0xc42065aa80, 0x525b8c0, 0xc420798d40, 0xc42028b800)
<autogenerated>:1 +0x8a fp=0xc4207dbb20 sp=0xc4207dba88 pc=0x4589aba
project/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42026bf20, 0x525b8c0, 0xc420798d40, 0xc42028b800)
/Users/james/www/gowork/src/project/vendor/github.com/gorilla/mux/mux.go:133 +0xed fp=0xc4207dbc20 sp=0xc4207dbb20 pc=0x42d577d
project/vendor/github.com/markbates/refresh/refresh/web.ErrorChecker.func1(0x525b8c0, 0xc420798d40, 0xc420121100)
/Users/james/www/gowork/src/project/vendor/github.com/markbates/refresh/refresh/web/web.go:23 +0xb1 fp=0xc4207dbcb0 sp=0xc4207dbc20 pc=0x435ddd1
net/http.HandlerFunc.ServeHTTP(0xc420798d60, 0x525b8c0, 0xc420798d40, 0xc420121100)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1918 +0x44 fp=0xc4207dbcd8 sp=0xc4207dbcb0 pc=0x4287dd4
project/vendor/github.com/gobuffalo/buffalo.(*App).ServeHTTP(0xc420340a00, 0x525b780, 0xc4206e0380, 0xc420121100)
/Users/james/www/gowork/src/project/vendor/github.com/gobuffalo/buffalo/app.go:120 +0x116 fp=0xc4207dbd18 sp=0xc4207dbcd8 pc=0x457a336
net/http.serverHandler.ServeHTTP(0xc420078000, 0x525b780, 0xc4206e0380, 0xc420121100)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2619 +0xb4 fp=0xc4207dbd48 sp=0xc4207dbd18 pc=0x428aa34
net/http.(*conn).serve(0xc4204106e0, 0x525db80, 0xc420615d00)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:1801 +0x71d fp=0xc4207dbfc8 sp=0xc4207dbd48 pc=0x4286cad
runtime.goexit()
/usr/local/Cellar/go/1.9.1/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4207dbfd0 sp=0xc4207dbfc8 pc=0x405a9f1
created by net/http.(*Server).Serve
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2720 +0x288

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x5b28f70, 0x72, 0xffffffffffffffff)
/usr/local/Cellar/go/1.9.1/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420250018, 0x72, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.9.1/libexec/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420250018, 0xffffffffffffff00, 0x0, 0x0)
/usr/local/Cellar/go/1.9.1/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420250000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.9.1/libexec/src/internal/poll/fd_unix.go:334 +0x1e2
net.(*netFD).accept(0xc420250000, 0x4c74108, 0xc420691cb8, 0x4003fdb)
/usr/local/Cellar/go/1.9.1/libexec/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e690, 0x4afdd80, 0xc420691ce8, 0x4002d77)
/usr/local/Cellar/go/1.9.1/libexec/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000e690, 0xc420691d30, 0xc420691d38, 0xc420691d28)
/usr/local/Cellar/go/1.9.1/libexec/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000e690, 0x4c729c8, 0xc420404320, 0x525dc40, 0xc420598a20)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc420078000, 0x525d440, 0xc42000e690, 0x0, 0x0)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc420078000, 0xc420078000, 0x0)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2636 +0xa9
net/http.ListenAndServe(0xc42024f970, 0xc, 0x5252440, 0xc420340a00, 0x1, 0xc42024f970)
/usr/local/Cellar/go/1.9.1/libexec/src/net/http/server.go:2882 +0x7f
main.startServer()
/Users/james/www/gowork/src/project/main.go:29 +0x1d7
main.main()
/Users/james/www/gowork/src/project/main.go:36 +0x184


```

**Comment by u007** [comment]
oh sorry i realize i open this type of error before
