### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by u007** [gobuffalo/buffalo#865]
buffalo 0.10.3
when building:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4352b99]

goroutine 8534 [running]:
github.com/gobuffalo/packr/builder.(*visitor).eval(0xc420f042d0, 0x4b53de0, 0xc42039a5d0, 0x0, 0x0)
	/Users/james/www/gowork/src/github.com/gobuffalo/packr/builder/visitor.go:88 +0x69
github.com/gobuffalo/packr/builder.(*visitor).Visit(0xc420f042d0, 0x4b53de0, 0xc42039a5d0, 0x4b4fba0, 0xc420f042d0)
	/Users/james/www/gowork/src/github.com/gobuffalo/packr/builder/visitor.go:69 +0x52
go/ast.Walk(0x4b4fba0, 0xc420f042d0, 0x4b53de0, 0xc42039a5d0)
	/usr/local/Cellar/go/1.9.2/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x4b4fba0, 0xc420f042d0, 0xc4203e2fc0, 0x4, 0x4)
	/usr/local/Cellar/go/1.9.2/libexec/src/go/ast/walk.go:38 +0x81
go/ast.Walk(0x4b4fba0, 0xc420f042d0, 0x4b53d60, 0xc4203ed480)
	/usr/local/Cellar/go/1.9.2/libexec/src/go/ast/walk.go:353 +0x2672
github.com/gobuffalo/packr/builder.(*visitor).Run(0xc420f042d0, 0x4bc6bf0, 0x5a)
	/Users/james/www/gowork/src/github.com/gobuffalo/packr/builder/visitor.go:42 +0x1e0
github.com/gobuffalo/packr/builder.(*Builder).process(0xc420010280, 0xc4200bdb00, 0x5a, 0xc421071f90, 0xffffffffffffffff)
	/Users/james/www/gowork/src/github.com/gobuffalo/packr/builder/builder.go:86 +0x194
github.com/gobuffalo/packr/builder.(*Builder).Run.func1.1(0xc400000008, 0x4832628)
	/Users/james/www/gowork/src/github.com/gobuffalo/packr/builder/builder.go:44 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc42005bec0, 0xc4202a8300)
	/Users/james/www/gowork/src/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/james/www/gowork/src/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by u007** [comment]
is this a packr issue?

**Comment by u007** [comment]
should there be a min dependency version to packr?

**Comment by u007** [comment]
sorry just found out that i duplicated vendor folder as vendorcache and it seems to fail after reading a go file in this folder
